#pragma once



enum PrimitiveType
{
    PRIMITIVE_PLANE,
    PRIMITIVE_CUBE,
    PRIMITIVE_CONE,
    PRIMITIVE_CYLINDER,
    PRIMITIVE_SPHERE,
    // ADD NEW PRIMITIVES HERE!!!


    /// ------ DO NOT TOUCH BELOW THIS LINE
    PRIMITIVE_MESH,
        // Hacky Solution, after mesh everything is generated by filename afterwards.
        // Ideally should be mapping from strings.
    STAIRS_STONE,
    TOWER_BASE,
    TOWER_SQUARE_BASE,
    TOWER_SQUARE,
    TOWER_SQUARE_ARCH,
    TOWER_SQUARE_MID,
    TOWER_SQUARE_ROOF,
    TOWER_SQUARE_TOP,
    WALL,
    WALL_CORNER,
    WALL_DOOR,
    WALL_HALF,
    WALL_CORNER_HALF_TOWER,
    TOWER_TOP_ROOF
};
